services:
  - type: web
    name: walkie-talkie-server-fix
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.cjs
    envVars:
      - key: PORT
        sync: false
