services:
  - type: web
    name: walkie-talkie-server-fix
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.cjs
    envVars:
      - key: PORT
        sync: false
      - key: SUPABASE_URL
        value: https://vzzjkoviyodurlzsiiup.supabase.co
      - key: SUPABASE_SERVICE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6emprb3ZpeW9kdXJsenNpaXVwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MDk5Mjc2MCwiZXhwIjoyMDg2NTY4NzYwfQ.7d5zzDtJ-JKILPnF44NVpBFKUptlXRyknThyhKoTrtY
